# pytest.ini
[pytest]
asyncio_mode=strict
testpaths =
    test
addopts =
    --ignore=test/test_runner.py
    --ignore=test/test_precision_multiplier.py
    --ignore=test/test_charli3_dendrite_adapter.py
    --ignore=test/test_generic_api_adapter.py
