"""updated to decimal

Revision ID: 7f3f195135b1
Revises: cdcc2afa5485
Create Date: 2024-05-29 19:57:26.767773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f3f195135b1'
down_revision: Union[str, None] = 'cdcc2afa5485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodeaggregation', 'aggregated_value',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('nodeupdate', 'updated_value',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodeupdate', 'updated_value',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('nodeaggregation', 'aggregated_value',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
