"""initial migration.

Revision ID: c42ba44f6aeb
Revises: 
Create Date: 2024-03-16 00:23:40.922052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c42ba44f6aeb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aggstate_nft', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oracle_nft', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_nft', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reward_nft', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oracle_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_id'), 'feed', ['id'], unique=False)
    op.create_table('operationalerror',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_traceback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operationalerror_id'), 'operationalerror', ['id'], unique=False)
    op.create_table('aggregatedratedetails',
    sa.Column('feed_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('aggregation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('aggregated_rate', sa.Numeric(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregatedratedetails_id'), 'aggregatedratedetails', ['id'], unique=False)
    op.create_table('job',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('schedule', sa.Numeric(), nullable=False),
    sa.Column('last_run_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('next_run_timestamp', sa.DateTime(), nullable=True),
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.ForeignKeyConstraint(['last_error_id'], ['operationalerror.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_id'), 'job', ['id'], unique=False)
    op.create_table('node',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('pub_key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_operator_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_id'), 'node', ['id'], unique=False)
    op.create_index(op.f('ix_node_pub_key_hash'), 'node', ['pub_key_hash'], unique=True)
    op.create_table('provider',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('adapter_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_id'), 'provider', ['id'], unique=False)
    op.create_table('nodeaggregation',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('node_pkh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aggregated_value', sa.Integer(), nullable=True),
    sa.Column('nodes_count', sa.Integer(), nullable=True),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.ForeignKeyConstraint(['node_pkh'], ['node.pub_key_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodeaggregation_id'), 'nodeaggregation', ['id'], unique=False)
    op.create_index(op.f('ix_nodeaggregation_tx_hash'), 'nodeaggregation', ['tx_hash'], unique=False)
    op.create_table('ratedataflow',
    sa.Column('provider_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('request_timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.Column('rate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate_aggregation_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.ForeignKeyConstraint(['rate_aggregation_id'], ['aggregatedratedetails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratedataflow_id'), 'ratedataflow', ['id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tx_fee', sa.Integer(), nullable=True),
    sa.Column('tx_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_tx_hash'), 'transaction', ['tx_hash'], unique=True)
    op.create_table('nodeaggregationparticipation',
    sa.Column('aggregation_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('node_pkh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aggregation_id'], ['nodeaggregation.id'], ),
    sa.ForeignKeyConstraint(['node_pkh'], ['node.pub_key_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodeaggregationparticipation_id'), 'nodeaggregationparticipation', ['id'], unique=False)
    op.create_table('nodeupdate',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_value', sa.Integer(), nullable=True),
    sa.Column('rate_aggregation_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['rate_aggregation_id'], ['aggregatedratedetails.id'], ),
    sa.ForeignKeyConstraint(['tx_hash'], ['transaction.tx_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodeupdate_id'), 'nodeupdate', ['id'], unique=False)
    op.create_index(op.f('ix_nodeupdate_tx_hash'), 'nodeupdate', ['tx_hash'], unique=False)
    op.create_table('rewarddistribution',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('node_pkh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_rewards_available', sa.Numeric(), nullable=False),
    sa.Column('aggregation_reward_increase', sa.Numeric(), nullable=False),
    sa.Column('node_aggregation_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['node_aggregation_id'], ['nodeaggregation.id'], ),
    sa.ForeignKeyConstraint(['node_pkh'], ['node.pub_key_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewarddistribution_id'), 'rewarddistribution', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewarddistribution_id'), table_name='rewarddistribution')
    op.drop_table('rewarddistribution')
    op.drop_index(op.f('ix_nodeupdate_tx_hash'), table_name='nodeupdate')
    op.drop_index(op.f('ix_nodeupdate_id'), table_name='nodeupdate')
    op.drop_table('nodeupdate')
    op.drop_index(op.f('ix_nodeaggregationparticipation_id'), table_name='nodeaggregationparticipation')
    op.drop_table('nodeaggregationparticipation')
    op.drop_index(op.f('ix_transaction_tx_hash'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_ratedataflow_id'), table_name='ratedataflow')
    op.drop_table('ratedataflow')
    op.drop_index(op.f('ix_nodeaggregation_tx_hash'), table_name='nodeaggregation')
    op.drop_index(op.f('ix_nodeaggregation_id'), table_name='nodeaggregation')
    op.drop_table('nodeaggregation')
    op.drop_index(op.f('ix_provider_id'), table_name='provider')
    op.drop_table('provider')
    op.drop_index(op.f('ix_node_pub_key_hash'), table_name='node')
    op.drop_index(op.f('ix_node_id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_job_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_aggregatedratedetails_id'), table_name='aggregatedratedetails')
    op.drop_table('aggregatedratedetails')
    op.drop_index(op.f('ix_operationalerror_id'), table_name='operationalerror')
    op.drop_table('operationalerror')
    op.drop_index(op.f('ix_feed_id'), table_name='feed')
    op.drop_table('feed')
    # ### end Alembic commands ###
