"""updated rate field.

Revision ID: cdcc2afa5485
Revises: c42ba44f6aeb
Create Date: 2024-03-31 18:04:46.472702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cdcc2afa5485'
down_revision: Union[str, None] = 'c42ba44f6aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratedataflow', 'rate',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratedataflow', 'rate',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
